"""add_budget_fields_to_task_requests

Revision ID: 396d4d5b5fb2
Revises: 7b2a1a7aa6a7
Create Date: 2026-03-12 10:38:25.354764
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396d4d5b5fb2'
down_revision: Union[str, None] = '7b2a1a7aa6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_requests', sa.Column('budget_min', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('task_requests', sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_requests', 'budget_max')
    op.drop_column('task_requests', 'budget_min')
    # ### end Alembic commands ###
