"""initial schema

Revision ID: ca3b042b2901
Revises: 
Create Date: 2026-03-04 09:34:00.091984
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3b042b2901'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CLIENT', 'SPECIALIST', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('specialist_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'specialist_id', name='uq_chatroom_client_specialist')
    )
    op.create_table('specialist_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Enum('AVAILABLE', 'BUSY', 'VACATION', name='availability'), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('specialist_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialist_id', 'client_id', name='uq_review_specialist_client')
    )
    op.create_table('specialist_competencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('specialist_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialist_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('specialist_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialist_languages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('specialist_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('proficiency', sa.Enum('BASIC', 'CONVERSATIONAL', 'FLUENT', 'NATIVE', name='languageproficiency'), nullable=False),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialist_languages')
    op.drop_table('specialist_domains')
    op.drop_table('specialist_competencies')
    op.drop_table('reviews')
    op.drop_table('messages')
    op.drop_table('specialist_profiles')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
